connect / as sysdba

DROP ROLE IPLABEL;
CREATE ROLE IPLABEL NOT IDENTIFIED;

GRANT CREATE VIEW TO IPLABEL;
GRANT CREATE TABLE TO IPLABEL;
GRANT CREATE PROCEDURE TO IPLABEL;
GRANT CREATE SEQUENCE TO IPLABEL;
GRANT CREATE TRIGGER TO IPLABEL;
GRANT EXECUTE ANY PROCEDURE TO IPLABEL;
/
exit
